% -------------------------------------------------------------------
%  Generated by MATLAB on 12-Apr-2021 23:05:31
%  MATLAB version: 9.6.0.1072779 (R2019a)
% -------------------------------------------------------------------
saveVarsMat = load('Lecture_9.mat');

C_pi = saveVarsMat.C_pi; % <1x1 pid> unsupported class

DEN = saveVarsMat.DEN; % <1x1 tf> unsupported class

NUM = 1;

continuousSystem = saveVarsMat.continuousSystem; % <1x1 tf> unsupported class

info = struct;
info.Stable = true;
info.CrossoverFrequency = 0.00029460966828383575;
info.PhaseMargin = 73.827309737318842;

s = saveVarsMat.s; % <1x1 tf> unsupported class

clear saveVarsMat;
